image:
 - Ubuntu

version: '{build}'

skip_tags: true
skip_commits:
  message: /[\[(^](do\s*n[o']?t\s*merge|wip|dnm)[\]):]/
  files:
    - '**/*.md'
    - docs/*

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

configuration: Release

nuget:
  disable_publish_on_pr: true

artifacts:
- path: .\.nupkgs\*.nupkg

build:
  project: OpenEventSourcing.sln
  verbosity: minimal

deploy:
  provider: NuGet
  api_key:
    secure: mD39v6YW1yjOg8vuxTU09TKocbbyR51UA0ghRdO8uqonIhzrIhUarLmQqIUDkoWG