image:
 - Ubuntu

services:
 - rabbitmq

version: '{build}'

skip_tags: true
skip_commits:
  message: /[\[(^](do\s*n[o']?t\s*merge|wip|dnm)[\]):]/
  files:
    - '**/*.md'
    - docs/*

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  OPENEVENTSOURCING_AZURE__SERVICEBUS__CONNECTIONSTRING:
    secure: 75AmcLvaIW2fdtqA8f771C+0MBNYFua+l7n+5w991QRmQszIi1DB1+AolYT3R7qEcV+6RQv7BpdGcrbokjOoG6QTt8bhclXN9yeVEnm/nwD9AJm5NaUASY6tY7NWpBL9OYklCDOIjPICehNMpc5iSYyq+xM6IziodGwYNIAfGJhscAjTKE19HszlgZ6djMH29pu4kIhvB5Lc6MPhQkmM67LWX6pOzkzum/QADLRodLc=

configuration: Release

for:
-
  branches:
    only: 
      - /release\/.+/
  deploy:
    - provider: NuGet
      api_key:
        secure: mD39v6YW1yjOg8vuxTU09TKocbbyR51UA0ghRdO8uqonIhzrIhUarLmQqIUDkoWG
    - provider: NuGet
      server: https://f.feedz.io/openeventsourcing/openeventsourcing/nuget/index.json
      api_key:
        secure: mGV8PYpl6myGMZKcFCcdIHmVZv2Y+vQPQ2yVizONSCsK2eRmaU7fsyjDgVl2MH4D
      symbol_server: https://f.feedz.io/openeventsourcing/openeventsourcing/symbols
-
  branches:
    only:
      - master
  deploy:
    - provider: NuGet
      server: https://ci.appveyor.com/nuget/danielcirket/api/v2/package
      api_key:
        secure: FnCP8/DuxKWcBh5XlDZ50fwxZObAi8Cfl26jYMAfdkU=
    - provider: NuGet
      server: https://f.feedz.io/openeventsourcing/openeventsourcing/nuget/index.json
      api_key:
        secure: mGV8PYpl6myGMZKcFCcdIHmVZv2Y+vQPQ2yVizONSCsK2eRmaU7fsyjDgVl2MH4D
      symbol_server: https://f.feedz.io/openeventsourcing/openeventsourcing/symbols

artifacts:
- path: .\.nupkgs\*.nupkg
- path: .\TestCoverage

before_build:
  - sudo rabbitmq-plugins enable rabbitmq_management

build:
  project: OpenEventSourcing.sln
  verbosity: minimal

test_script:
  - dotnet test /p:CollectCoverage=true /p:CoverletOutput='../../TestCoverage/' /p:MergeWith='../../TestCoverage/coverage.json' /p:CoverletOutputFormat="opencover" /p:Exclude="[OpenEventSourcing.Samples.*]"

nuget:
  disable_publish_on_pr: true
  project_feed: true