image:
 - Ubuntu

services:
 - rabbitmq

version: '{build}'

skip_tags: true
skip_commits:
  message: /[\[(^](do\s*n[o']?t\s*merge|wip|dnm)[\]):]/
  files:
    - '**/*.md'
    - docs/*

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

configuration: Release

for:
-
  branches:
    only: 
      - /release\/.+/
  deploy:
    - provider: NuGet
      api_key:
        secure: mD39v6YW1yjOg8vuxTU09TKocbbyR51UA0ghRdO8uqonIhzrIhUarLmQqIUDkoWG

artifacts:
- path: .\.nupkgs\*.nupkg

build:
  project: OpenEventSourcing.sln
  verbosity: minimal

nuget:
  disable_publish_on_pr: true
  project_feed: true

deploy:
    - provider: NuGet
      server: https://ci.appveyor.com/nuget/danielcirket/api/v2/package
      api_key:
        secure: FnCP8/DuxKWcBh5XlDZ50fwxZObAi8Cfl26jYMAfdkU=